import { IJimuApiOption } from "@jimengio/api-base";
import { Id, EApiKind } from "../src/types";
import { insertPublicHost } from "./configs";
import {
  ajaxGet,
  ajaxDelete,
  ajaxPost,
  ajaxPut,
  hooksGet,
  hooksPost,
  hooksPut,
  hooksDelete,
  dynamicGet,
  dynamicPost,
  dynamicPut,
  dynamicDelete,
} from "../src/funcs";

/** Generated by generator */

export let genSeedApiTree = {
  user: {
    accesses: {
      _: {
        /** 删除登录记录 */
        GET: (id: Id, opts?: IJimuApiOption) => ajaxGet<IApiResultGet_UserAccesses_>(insertPublicHost("/user/accesses/{id}"), `/user/accesses/${id}`, {}, opts),
        /** 删除登录记录 */
        useGET: (id: Id, opts?: IJimuApiOption) =>
          hooksGet<IApiResultGet_UserAccesses_>(insertPublicHost("/user/accesses/{id}"), `/user/accesses/${id}`, {}, opts),
        /** 删除登录记录 */
        dynamicGET: () => dynamicGet<IApiResultGet_UserAccesses_, {}, { id: Id }>(insertPublicHost("/user/accesses/{id}"), "/user/accesses/${id}"),
      },
    },
    info: {
      /** 更新用户信息 */
      POST: (body: IApiBodyPost_UserInfo, opts?: IJimuApiOption) =>
        ajaxPost<IApiResultPost_UserInfo>(insertPublicHost("/user/info"), `/user/info`, body, {}, opts),
      /** 更新用户信息 */
      usePOST: () => hooksPost<IApiResultPost_UserInfo, IApiBodyPost_UserInfo>(insertPublicHost("/user/info"), `/user/info`),
      /** 更新用户信息 */
      dynamicPOST: () => dynamicPost<IApiResultPost_UserInfo, IApiBodyPost_UserInfo, {}, {}>(insertPublicHost("/user/info"), "/user/info"),
      /** 更新用户信息 */
      PUT: (body: IApiBodyPut_UserInfo, opts?: IJimuApiOption) => ajaxPut<IApiResultPut_UserInfo>(insertPublicHost("/user/info"), `/user/info`, body, {}, opts),
      /** 更新用户信息 */
      usePUT: () => hooksPut<IApiResultPut_UserInfo, IApiBodyPut_UserInfo>(insertPublicHost("/user/info"), `/user/info`),
      /** 更新用户信息 */
      dynamicPUT: () => dynamicPut<IApiResultPut_UserInfo, IApiBodyPut_UserInfo, {}, {}>(insertPublicHost("/user/info"), "/user/info"),
    },
    me: {
      /** 用户信息 */
      GET: (q?: IApiQuery_UserMe, opts?: IJimuApiOption) => ajaxGet<IApiResultGet_UserMe>(insertPublicHost("/user/me"), `/user/me`, q, opts),
      /** 用户信息 */
      useGET: (q?: IApiQuery_UserMe, opts?: IJimuApiOption) =>
        hooksGet<IApiResultGet_UserMe, IApiQuery_UserMe>(insertPublicHost("/user/me"), `/user/me`, q, opts),
      /** 用户信息 */
      dynamicGET: () => dynamicGet<IApiResultGet_UserMe, IApiQuery_UserMe, {}>(insertPublicHost("/user/me"), "/user/me"),
    },
  },
};

export interface IApiBodyPost_UserInfo {
  name: string;
  gender: string;
}
export interface IApiBodyPut_UserInfo {
  id?: string;
  name?: string;
  position?: { id: string; name: string };
}
export interface IApiQuery_UserMe {
  /** 包含详细信息 */
  withPosition?: any;
}
export interface IApiResultGet_UserAccesses_ {}
export interface IApiResultGet_UserMe {
  id: string;
  name: string;
  position?: { id?: string; name?: string };
}
export interface IApiResultPost_UserInfo {
  id: string;
  name: string;
}
export interface IApiResultPut_UserInfo {
  id: string;
  name: string;
  position: { id: string; name: string };
}
