import { IJimuApiOption } from "@jimengio/api-base";
import { Id, EApiKind } from "./types";
import { insertPublicHost } from "./configs";
import {
  ajaxGet,
  ajaxDelete,
  ajaxPost,
  ajaxPut,
  hooksGet,
  hooksPost,
  hooksPut,
  hooksDelete,
  dynamicGet,
  dynamicPost,
  dynamicPut,
  dynamicDelete,
} from "./funcs";

/** Generated by generator */

export let genSeedApiTree = {};
